lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: Adam's Website
description: This is my website
theme: jekyll-theme-minimal